services:
  # Jexxl API Flask App
  flaskapp:
    build: ./flaskapp
    image: flaskapp-jexxl-api
    container_name: flaskapp
    ports:
      - "65190:65190"
    volumes:
      - ./flaskapp:/app/flaskapp
      - ./raml:/app/raml
    networks:
      - jexxl2-network

networks:
  jexxl2-network:
    external: true