services:
  # Jexxl API Flask App
  flaskapp:
    build: ./flaskapp
    image: jexxl-flaskapp
    container_name: flaskapp
    ports:
      - "65190:65190"
    volumes:
      - ./flaskapp/access.log:/app/flaskapp/access.log
      - ./flaskapp/templates:/app/flaskapp/templates
      - ./flaskapp/static:/app/flaskapp/static
    networks:
      - jexxl2-network

  # Jexxl API Documentation
  api-docs:
    image: redocly/redoc:latest
    container_name: api-docs
    ports:
      - "65200:80"
    volumes:
      - ./flaskapp/redoc/openapi.yaml:/usr/share/nginx/html/openapi.yaml
      - ./flaskapp/static/images/api-logo.svg:/usr/share/nginx/html/api-logo.svg
    environment:
      SPEC_URL: /openapi.yaml
      PAGE_FAVICON: /api-logo.svg
      PAGE_TITLE: Jexxl API Docs
      REDOC_OPTIONS: >-
        disable-search=true
    networks:
      - jexxl2-network

networks:
  jexxl2-network:
    external: true